apiVersion: v1
kind: Service
metadata:
  labels:
    app: celeste-lopez-e2e-assignment
    app.kubernetes.io/instance: celeste-lopez-e2e-assignment
    app.kubernetes.io/name: celeste-lopez-e2e-assignment-celeste-lopez-e2e-assignment
  name: celeste-lopez-e2e-assignment
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: celeste-lopez-e2e-assignment
    app.kubernetes.io/instance: celeste-lopez-e2e-assignment
    app.kubernetes.io/name: celeste-lopez-e2e-assignment-celeste-lopez-e2e-assignment
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: f7580aa1eb6f7176705176e201ecff4de93edafb
    app.openshift.io/vcs-uri: https://github.com/upslopeio/express-sample-app
  labels:
    app: celeste-lopez-e2e-assignment
    app.kubernetes.io/instance: celeste-lopez-e2e-assignment
    app.kubernetes.io/name: celeste-lopez-e2e-assignment-celeste-lopez-e2e-assignment
    app.openshift.io/runtime: js
  name: celeste-lopez-e2e-assignment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: celeste-lopez-e2e-assignment
      app.kubernetes.io/instance: celeste-lopez-e2e-assignment
      app.kubernetes.io/name: celeste-lopez-e2e-assignment-celeste-lopez-e2e-assignment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: celeste-lopez-e2e-assignment
        app.kubernetes.io/instance: celeste-lopez-e2e-assignment
        app.kubernetes.io/name: celeste-lopez-e2e-assignment-celeste-lopez-e2e-assignment
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/celestelopezgarrido/celeste-lopez-e2e-assignment:14475291500b02b78823e68c7ac9ae0b1167974b
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: celeste-lopez-e2e-assignment
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: celeste-lopez-e2e-assignment
    app.kubernetes.io/instance: celeste-lopez-e2e-assignment
    app.kubernetes.io/name: celeste-lopez-e2e-assignment-celeste-lopez-e2e-assignment
  name: celeste-lopez-e2e-assignment
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: celeste-lopez-e2e-assignment
    weight: 100
  wildcardPolicy: None
