apiVersion: v1
kind: Service
metadata:
  labels:
    app: alexandra-molnar-next-app
    app.kubernetes.io/instance: alexandra-molnar-next-app
    app.kubernetes.io/name: alexandra-molnar-next-app-next-app
  name: next-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: alexandra-molnar-next-app
    app.kubernetes.io/instance: alexandra-molnar-next-app
    app.kubernetes.io/name: alexandra-molnar-next-app-next-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alexandra-molnar-next-app
    app.kubernetes.io/instance: alexandra-molnar-next-app
    app.kubernetes.io/name: alexandra-molnar-next-app-next-app
    app.openshift.io/runtime: js
  name: next-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alexandra-molnar-next-app
      app.kubernetes.io/instance: alexandra-molnar-next-app
      app.kubernetes.io/name: alexandra-molnar-next-app-next-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alexandra-molnar-next-app
        app.kubernetes.io/instance: alexandra-molnar-next-app
        app.kubernetes.io/name: alexandra-molnar-next-app-next-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/adelaalexa0/next-app:39d2094626ffb69a6167172a8c95cba2ad49ad87
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: next-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: alexandra-molnar-next-app
    app.kubernetes.io/instance: alexandra-molnar-next-app
    app.kubernetes.io/name: alexandra-molnar-next-app-next-app
  name: next-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: next-app
    weight: 100
  wildcardPolicy: None
