apiVersion: v1
kind: Service
metadata:
  labels:
    app: daniele-scaramuzzi-pipeline-from-scratch
    app.kubernetes.io/instance: daniele-scaramuzzi-pipeline-from-scratch
    app.kubernetes.io/name: daniele-scaramuzzi-pipeline-from-scratch-scara-dotnet-web-app
  name: scara-dotnet-web-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: daniele-scaramuzzi-pipeline-from-scratch
    app.kubernetes.io/instance: daniele-scaramuzzi-pipeline-from-scratch
    app.kubernetes.io/name: daniele-scaramuzzi-pipeline-from-scratch-scara-dotnet-web-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: f7580aa1eb6f7176705176e201ecff4de93edafb
    app.openshift.io/vcs-uri: https://github.com/danielescaramuzzi/dotnet-core-sample
  labels:
    app: daniele-scaramuzzi-pipeline-from-scratch
    app.kubernetes.io/instance: daniele-scaramuzzi-pipeline-from-scratch
    app.kubernetes.io/name: daniele-scaramuzzi-pipeline-from-scratch-scara-dotnet-web-app
    app.openshift.io/runtime: dotnet
  name: scara-dotnet-web-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: daniele-scaramuzzi-pipeline-from-scratch
      app.kubernetes.io/instance: daniele-scaramuzzi-pipeline-from-scratch
      app.kubernetes.io/name: daniele-scaramuzzi-pipeline-from-scratch-scara-dotnet-web-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: daniele-scaramuzzi-pipeline-from-scratch
        app.kubernetes.io/instance: daniele-scaramuzzi-pipeline-from-scratch
        app.kubernetes.io/name: daniele-scaramuzzi-pipeline-from-scratch-scara-dotnet-web-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/danielescaramuzzi/scara-dotnet-web-app:bea337526853d5418a765f213aef10ea1068cb29
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: scara-dotnet-web-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: daniele-scaramuzzi-pipeline-from-scratch
    app.kubernetes.io/instance: daniele-scaramuzzi-pipeline-from-scratch
    app.kubernetes.io/name: daniele-scaramuzzi-pipeline-from-scratch-scara-dotnet-web-app
  name: scara-dotnet-web-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: scara-dotnet-web-app
    weight: 100
  wildcardPolicy: None
