apiVersion: v1
kind: Service
metadata:
  labels:
    app: nicola-bertoli-pipelines-project
    app.kubernetes.io/instance: nicola-bertoli-pipelines-project
    app.kubernetes.io/name: nicola-bertoli-pipelines-project-buildah-assignment
  name: buildah-assignment
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nicola-bertoli-pipelines-project
    app.kubernetes.io/instance: nicola-bertoli-pipelines-project
    app.kubernetes.io/name: nicola-bertoli-pipelines-project-buildah-assignment
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: f7580aa1eb6f7176705176e201ecff4de93edafb
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/nicola-bertoli-app
  labels:
    app: nicola-bertoli-pipelines-project
    app.kubernetes.io/instance: nicola-bertoli-pipelines-project
    app.kubernetes.io/name: nicola-bertoli-pipelines-project-buildah-assignment
    app.openshift.io/runtime: js
  name: buildah-assignment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nicola-bertoli-pipelines-project
      app.kubernetes.io/instance: nicola-bertoli-pipelines-project
      app.kubernetes.io/name: nicola-bertoli-pipelines-project-buildah-assignment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nicola-bertoli-pipelines-project
        app.kubernetes.io/instance: nicola-bertoli-pipelines-project
        app.kubernetes.io/name: nicola-bertoli-pipelines-project-buildah-assignment
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/nicolabe92/buildah-assignment:843e0cd9342521771274221015613649421bd96c
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: buildah-assignment
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: nicola-bertoli-pipelines-project
    app.kubernetes.io/instance: nicola-bertoli-pipelines-project
    app.kubernetes.io/name: nicola-bertoli-pipelines-project-buildah-assignment
  name: buildah-assignment
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: buildah-assignment
    weight: 100
  wildcardPolicy: None
