apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipeline-e2e-lumino
    app.kubernetes.io/instance: pipeline-e2e-lumino
    app.kubernetes.io/name: pipeline-e2e-lumino-lumander-next-js
  name: lumander-next-js
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: pipeline-e2e-lumino
    app.kubernetes.io/instance: pipeline-e2e-lumino
    app.kubernetes.io/name: pipeline-e2e-lumino-lumander-next-js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: f7580aa1eb6f7176705176e201ecff4de93edafb
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/lumander-next-js
  labels:
    app: pipeline-e2e-lumino
    app.kubernetes.io/instance: pipeline-e2e-lumino
    app.kubernetes.io/name: pipeline-e2e-lumino-lumander-next-js
    app.openshift.io/runtime: js
  name: lumander-next-js
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pipeline-e2e-lumino
      app.kubernetes.io/instance: pipeline-e2e-lumino
      app.kubernetes.io/name: pipeline-e2e-lumino-lumander-next-js
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pipeline-e2e-lumino
        app.kubernetes.io/instance: pipeline-e2e-lumino
        app.kubernetes.io/name: pipeline-e2e-lumino-lumander-next-js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/lumander/lumander-next-js:2f772c40d00b9352023e8629b3c66967ff4a2bea
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: lumander-next-js
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: pipeline-e2e-lumino
    app.kubernetes.io/instance: pipeline-e2e-lumino
    app.kubernetes.io/name: pipeline-e2e-lumino-lumander-next-js
  name: lumander-next-js
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: lumander-next-js
    weight: 100
  wildcardPolicy: None
